version: "3.8"

services:
  java-app:
    image: maven:3.8.6-openjdk-11
    working_dir: /app
    volumes:
      - ./:/app
      - ~/.m2:/root/.m2
      - ./lib:/app/lib  # monte a pasta onde está o driver PostgreSQL
    command: tail -f /dev/null
    depends_on:
      - postgres-db
    environment:
      - DB_HOST=postgres-db
      - DB_PORT=5432
      - DB_NAME=app_db
      - DB_USER=devuser
      - DB_PASSWORD=devpassword
    networks:
      - auri-network

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - auri-network

volumes:
  postgres_data:

networks:
  auri-network:
